### ISSUE TITLE
has_openmm needs to work in python 3.6

### ISSUE THREAD

**Issue by umesh-timalsina** [mosdef-hub/gmso#411]
Python 3.6 ([`gmso/utils/io.py`](https://github.com/mosdef-hub/gmso/blob/master/gmso/utils/io.py#L109-L114))
```py
(gmso-dev-py36) umesh@isisdell:~/work/mosdef-hub/gmso(408-azp-pyversion)$ python
Python 3.6.10 | packaged by conda-forge | (default, Apr 24 2020, 16:44:11) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simtk.openmm
>>> del simtk.openmm
>>> import simtk.openmm
>>> import simtk.openmm as mm  # (Required by parmed `load_topology`)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'simtk' has no attribute 'openmm'
>>> 
```
Python 3.7
```py
(gmso-dev) umesh@isisdell:~/work/mosdef-hub/gmso(408-azp-pyversion)$ python
Python 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import simtk.openmm 
>>> del simtk.openmm
>>> import simtk.openmm as mm
>>> 

```
